name:                PropaFP
version:             0.1.1.0
github:              "rasheedja/PropaFP"
license:             MPL-2.0
author:              "Junaid Rasheed"
maintainer:          "jrasheed178@gmail.com"
copyright:           "MPL-2.0"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
synopsis:            Auto-active verification of floating-point programs
category:            Math, Maths, Mathematics, Formal methods, Theorem Provers

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/rasheedja/PropaFP#readme>

dependencies:
- base >= 4.7 && < 5
- mixed-types-num >= 0.5.10 && < 0.6
- aern2-mfun >= 0.2.9 && < 0.3
- aern2-mp >= 0.2.9.1 && < 0.3
- collect-errors >= 0.1.5 && < 0.2
- containers >= 0.6.4.1 && < 0.7
- extra >= 1.7.10 && < 1.8
- QuickCheck >= 2.14.2 && < 2.15
- ghc >= 9.0.2 && < 9.1
- scientific >= 0.3.7.0 && < 0.4
- binary >= 0.8.8.0 && < 0.9
- regex-tdfa >= 1.3.1.2 && < 1.4
- temporary >= 1.3 && < 1.4
- bytestring >= 0.10.12.1 && < 0.11
- process >= 1.6.13.2 && < 1.7
- directory >= 1.3.6.2 && < 1.4
- optparse-applicative >= 0.16.1.0 && < 0.17

default-extensions:
- RebindableSyntax,
- ScopedTypeVariables,
- TypeFamilies,
- TypeOperators,
- ConstraintKinds,
- DefaultSignatures,
- MultiParamTypeClasses,
- FlexibleContexts,
- FlexibleInstances,
- UndecidableInstances

library:
  source-dirs: src

executables:
  propafp-translate-dreal:
    main:                app/DRealTranslator.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    - -O2
    dependencies:
    - PropaFP
  propafp-translate-metitarski:
    main:                app/MetiTarskiTranslator.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    - -O2
    dependencies:
    - PropaFP
  propafp-prettify:
    main:                app/PrettifySMT2.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    - -O2
    dependencies:
    - PropaFP
  propafp-run-dreal:
    main:                app/DRealRunner.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    - -O2
    dependencies:
    - PropaFP
  propafp-run-lppaver:
    main:                app/LPPaverRunner.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    - -O2
    dependencies:
    - PropaFP
  propafp-run-metitarski:
    main:                app/MetiTarskiRunner.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    - -O2
    dependencies:
    - PropaFP

tests:
  PropaFP-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - PropaFP
